---
# This is the checkov workflow with actions
# To get the value of LW_IAC_ORGANIZATION, login into "Laceworks IaC UI" https://app.soluble.cloud and authenticate with personal GitHub credentials.
# To get the value of SOLUBLE_API_TOKEN, go to the URL https://app.soluble.cloud/admin/tokens/access and generate an access token.
on: [push]  # yamllint disable-line rule:truthy
jobs:
  # checkov-job:
  #    needs: yamllint
  #   runs-on: ubuntu-latest
  #   name: checkov-action
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@master
  #     - name: wget the config file
  #        yamllint disable
  #       run: mkdir config && wget -O config/checkov_config.yaml https://raw.githubusercontent.com/sun1l-aries/checkov_config/master/config_output.yaml
  #        yamllint enable
  #     - name: pull the docker
  #       run: docker pull bridgecrew/checkov
  #     - name: mount the 2 volumes and run checkov
  #        yamllint disable
  #       run: docker run --tty --volume $(pwd):/tf --workdir /tf bridgecrew/checkov --config-file /tf/config/checkov_config.yaml
  #        yamllint enable
  # This is the soluble cli workflow with actions
  soluble-cli-job:
    runs-on: ubuntu-latest
    name: soluble-cli-scan
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      # - name: pull the soluble cli container docker
      #   run: docker pull ryansheldrakelw/soluble-scan
      - name: Run the docker container. Instructions in last email from Ryan on the dockerhub page
        run: docker run -t -v $(pwd):/tmp/soluble-temp -e SOLUBLE_API_TOKEN="eyJraWQiOiJzand0LWEyYTM1YmFlIiwiYWxnIjoiSFMyNTYifQ.eyJhdWQiOiJ1c2VyIiwiZXhwIjo0MTAyNDQ0ODAwLCJpYXQiOjE2NzExNDIyOTYsInN1YiI6InUtNWZkYjliMjI5Y2YxOTNkYyIsIm9yZyI6IjI2MjI0MDcyMDUwMiJ9.R4CcKn7OuuBXkyoK1wJVTyMHi3QsXC4NOpAso9TSThw" -e LW_IAC_ORGANIZATION=${{env.LW_IAC_ORGANIZATION}} ryansheldrakelw/soluble-scan
        # run: docker run -t -v $(pwd):/tmp/soluble-temp -e SOLUBLE_API_TOKEN="eyJraWQiOiJzand0LWEyYTM1YmFlIiwiYWxnIjoiSFMyNTYifQ.eyJhdWQiOiJ1c2VyIiwiZXhwIjo0MTAyNDQ0ODAwLCJpYXQiOjE2NzExNDIyOTYsInN1YiI6InUtNWZkYjliMjI5Y2YxOTNkYyIsIm9yZyI6IjI2MjI0MDcyMDUwMiJ9.R4CcKn7OuuBXkyoK1wJVTyMHi3QsXC4NOpAso9TSThw" -e LW_IAC_ORGANIZATION="262240720502" ryansheldrakelw/soluble-scan
